name: Central AI Blog Agent

on:
  workflow_call:
    inputs:
      target_repo:
        required: true
        type: string
      target_branch:
        required: true
        type: string

jobs:
  generate_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AI Agent Repo
        uses: actions/checkout@v4
        with:
          repository: Gaurav0807/ai-blog-agents
          path: ai-agent

      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target_repo }}
          ref: ${{ inputs.target_branch }}
          path: target-repo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ai-agent
        run: pip install -r requirements.txt

      - name: Run AI Agent
        working-directory: ai-agent
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: python agent.py ../target-repo

      - name: Commit blog to target repo path
        run: |
          cd target-repo
          git config user.name "Gaurav0807"
          git config user.email "gauravrawat141999@gmail.com"
          git add medium_blog.md
          git commit -m "docs(ai): auto-generate for medium blog" || echo "No changes"
          git push