name: Trigger AI Blog

on:
  push:
    branches: [ "main" ]

permissions:
  contents: writ
  
jobs:
  call-agent:
    if: contains(github.event.head_commit.message, 'ai-blog')
    uses: Gaurav0807/ai-blog-agents/.github/workflows/run-agent.yml@main
    with:
      target_repo: ${{ github.repository }}
      target_branch: main
    secrets: inherit